//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace image.ImageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageClass", Namespace="http://schemas.datacontract.org/2004/07/Network.Images")]
    [System.SerializableAttribute()]
    public partial class ImageClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int image_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.exceptionField, value) != true)) {
                    this.exceptionField = value;
                    this.RaisePropertyChanged("exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int image_id {
            get {
                return this.image_idField;
            }
            set {
                if ((this.image_idField.Equals(value) != true)) {
                    this.image_idField = value;
                    this.RaisePropertyChanged("image_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_url {
            get {
                return this.image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.image_urlField, value) != true)) {
                    this.image_urlField = value;
                    this.RaisePropertyChanged("image_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/Network")]
    [System.SerializableAttribute()]
    public partial class Picture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string current_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_deleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_uploadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool deletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> have_miniatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string start_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string current_name {
            get {
                return this.current_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.current_nameField, value) != true)) {
                    this.current_nameField = value;
                    this.RaisePropertyChanged("current_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_delete {
            get {
                return this.date_deleteField;
            }
            set {
                if ((this.date_deleteField.Equals(value) != true)) {
                    this.date_deleteField = value;
                    this.RaisePropertyChanged("date_delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_upload {
            get {
                return this.date_uploadField;
            }
            set {
                if ((this.date_uploadField.Equals(value) != true)) {
                    this.date_uploadField = value;
                    this.RaisePropertyChanged("date_upload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                if ((this.deletedField.Equals(value) != true)) {
                    this.deletedField = value;
                    this.RaisePropertyChanged("deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> have_miniature {
            get {
                return this.have_miniatureField;
            }
            set {
                if ((this.have_miniatureField.Equals(value) != true)) {
                    this.have_miniatureField = value;
                    this.RaisePropertyChanged("have_miniature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_owner {
            get {
                return this.id_ownerField;
            }
            set {
                if ((this.id_ownerField.Equals(value) != true)) {
                    this.id_ownerField = value;
                    this.RaisePropertyChanged("id_owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string start_name {
            get {
                return this.start_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.start_nameField, value) != true)) {
                    this.start_nameField = value;
                    this.RaisePropertyChanged("start_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Album", Namespace="http://schemas.datacontract.org/2004/07/Network")]
    [System.SerializableAttribute()]
    public partial class Album : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> date_deleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool deletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string photosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_creation {
            get {
                return this.date_creationField;
            }
            set {
                if ((this.date_creationField.Equals(value) != true)) {
                    this.date_creationField = value;
                    this.RaisePropertyChanged("date_creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> date_delete {
            get {
                return this.date_deleteField;
            }
            set {
                if ((this.date_deleteField.Equals(value) != true)) {
                    this.date_deleteField = value;
                    this.RaisePropertyChanged("date_delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                if ((this.deletedField.Equals(value) != true)) {
                    this.deletedField = value;
                    this.RaisePropertyChanged("deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_owner {
            get {
                return this.id_ownerField;
            }
            set {
                if ((this.id_ownerField.Equals(value) != true)) {
                    this.id_ownerField = value;
                    this.RaisePropertyChanged("id_owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string photos {
            get {
                return this.photosField;
            }
            set {
                if ((object.ReferenceEquals(this.photosField, value) != true)) {
                    this.photosField = value;
                    this.RaisePropertyChanged("photos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageService.IImageService")]
    public interface IImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadImage", ReplyAction="http://tempuri.org/IImageService/UploadImageResponse")]
        image.ImageService.ImageClass UploadImage(byte[] buffer, string name, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadImage", ReplyAction="http://tempuri.org/IImageService/UploadImageResponse")]
        System.Threading.Tasks.Task<image.ImageService.ImageClass> UploadImageAsync(byte[] buffer, string name, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadMiniature", ReplyAction="http://tempuri.org/IImageService/UploadMiniatureResponse")]
        image.ImageService.ImageClass UploadMiniature(byte[] buffer, int id_image, string urlid, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadMiniature", ReplyAction="http://tempuri.org/IImageService/UploadMiniatureResponse")]
        System.Threading.Tasks.Task<image.ImageService.ImageClass> UploadMiniatureAsync(byte[] buffer, int id_image, string urlid, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadAvatar", ReplyAction="http://tempuri.org/IImageService/UploadAvatarResponse")]
        image.ImageService.ImageClass UploadAvatar(byte[] buffer, string name, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/UploadAvatar", ReplyAction="http://tempuri.org/IImageService/UploadAvatarResponse")]
        System.Threading.Tasks.Task<image.ImageService.ImageClass> UploadAvatarAsync(byte[] buffer, string name, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageUrlById", ReplyAction="http://tempuri.org/IImageService/GetImageUrlByIdResponse")]
        string GetImageUrlById(int id_image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageUrlById", ReplyAction="http://tempuri.org/IImageService/GetImageUrlByIdResponse")]
        System.Threading.Tasks.Task<string> GetImageUrlByIdAsync(int id_image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageById", ReplyAction="http://tempuri.org/IImageService/GetImageByIdResponse")]
        image.ImageService.Picture GetImageById(int id_image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageById", ReplyAction="http://tempuri.org/IImageService/GetImageByIdResponse")]
        System.Threading.Tasks.Task<image.ImageService.Picture> GetImageByIdAsync(int id_image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/DeleteImage", ReplyAction="http://tempuri.org/IImageService/DeleteImageResponse")]
        bool DeleteImage(int id_image, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/DeleteImage", ReplyAction="http://tempuri.org/IImageService/DeleteImageResponse")]
        System.Threading.Tasks.Task<bool> DeleteImageAsync(int id_image, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/CreateAlbum", ReplyAction="http://tempuri.org/IImageService/CreateAlbumResponse")]
        image.ImageService.Album CreateAlbum(string name, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/CreateAlbum", ReplyAction="http://tempuri.org/IImageService/CreateAlbumResponse")]
        System.Threading.Tasks.Task<image.ImageService.Album> CreateAlbumAsync(string name, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/AddImageToAlbum", ReplyAction="http://tempuri.org/IImageService/AddImageToAlbumResponse")]
        image.ImageService.Album AddImageToAlbum(byte[] image, string name, int id_album, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/AddImageToAlbum", ReplyAction="http://tempuri.org/IImageService/AddImageToAlbumResponse")]
        System.Threading.Tasks.Task<image.ImageService.Album> AddImageToAlbumAsync(byte[] image, string name, int id_album, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/DeleteImageFromAlbum", ReplyAction="http://tempuri.org/IImageService/DeleteImageFromAlbumResponse")]
        bool DeleteImageFromAlbum(int id_image, int id_album, int id_user, string access_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/DeleteImageFromAlbum", ReplyAction="http://tempuri.org/IImageService/DeleteImageFromAlbumResponse")]
        System.Threading.Tasks.Task<bool> DeleteImageFromAlbumAsync(int id_image, int id_album, int id_user, string access_token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageServiceChannel : image.ImageService.IImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceClient : System.ServiceModel.ClientBase<image.ImageService.IImageService>, image.ImageService.IImageService {
        
        public ImageServiceClient() {
        }
        
        public ImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public image.ImageService.ImageClass UploadImage(byte[] buffer, string name, int id_user, string access_token) {
            return base.Channel.UploadImage(buffer, name, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<image.ImageService.ImageClass> UploadImageAsync(byte[] buffer, string name, int id_user, string access_token) {
            return base.Channel.UploadImageAsync(buffer, name, id_user, access_token);
        }
        
        public image.ImageService.ImageClass UploadMiniature(byte[] buffer, int id_image, string urlid, int id_user, string access_token) {
            return base.Channel.UploadMiniature(buffer, id_image, urlid, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<image.ImageService.ImageClass> UploadMiniatureAsync(byte[] buffer, int id_image, string urlid, int id_user, string access_token) {
            return base.Channel.UploadMiniatureAsync(buffer, id_image, urlid, id_user, access_token);
        }
        
        public image.ImageService.ImageClass UploadAvatar(byte[] buffer, string name, int id_user, string access_token) {
            return base.Channel.UploadAvatar(buffer, name, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<image.ImageService.ImageClass> UploadAvatarAsync(byte[] buffer, string name, int id_user, string access_token) {
            return base.Channel.UploadAvatarAsync(buffer, name, id_user, access_token);
        }
        
        public string GetImageUrlById(int id_image) {
            return base.Channel.GetImageUrlById(id_image);
        }
        
        public System.Threading.Tasks.Task<string> GetImageUrlByIdAsync(int id_image) {
            return base.Channel.GetImageUrlByIdAsync(id_image);
        }
        
        public image.ImageService.Picture GetImageById(int id_image) {
            return base.Channel.GetImageById(id_image);
        }
        
        public System.Threading.Tasks.Task<image.ImageService.Picture> GetImageByIdAsync(int id_image) {
            return base.Channel.GetImageByIdAsync(id_image);
        }
        
        public bool DeleteImage(int id_image, int id_user, string access_token) {
            return base.Channel.DeleteImage(id_image, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteImageAsync(int id_image, int id_user, string access_token) {
            return base.Channel.DeleteImageAsync(id_image, id_user, access_token);
        }
        
        public image.ImageService.Album CreateAlbum(string name, int id_user, string access_token) {
            return base.Channel.CreateAlbum(name, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<image.ImageService.Album> CreateAlbumAsync(string name, int id_user, string access_token) {
            return base.Channel.CreateAlbumAsync(name, id_user, access_token);
        }
        
        public image.ImageService.Album AddImageToAlbum(byte[] image, string name, int id_album, int id_user, string access_token) {
            return base.Channel.AddImageToAlbum(image, name, id_album, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<image.ImageService.Album> AddImageToAlbumAsync(byte[] image, string name, int id_album, int id_user, string access_token) {
            return base.Channel.AddImageToAlbumAsync(image, name, id_album, id_user, access_token);
        }
        
        public bool DeleteImageFromAlbum(int id_image, int id_album, int id_user, string access_token) {
            return base.Channel.DeleteImageFromAlbum(id_image, id_album, id_user, access_token);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteImageFromAlbumAsync(int id_image, int id_album, int id_user, string access_token) {
            return base.Channel.DeleteImageFromAlbumAsync(id_image, id_album, id_user, access_token);
        }
    }
}
